import sqlite3
import pandas as pd

# ---------------------------------------------------------
# 1. 번역 데이터 (여기에만 유지)
# ---------------------------------------------------------
RAW_DATA = {
    "English": {
        "app_title": "K-Used Car Global Hub",
        "login_title": "Login",
        "id": "ID",
        "pw": "Password",
        "sign_in": "Sign In",
        "logout": "Logout",
        "welcome": "Welcome, {}!",
        "invalid_cred": "Invalid Credentials",
        "admin_tools": "Admin Tools",
        "data_upload": "Data Upload",
        "save_data": "Save Data",
        "addr_db": "Address DB",
        "save_addr": "Save Address",
        "reset_db": "Reset DB",
        "reset_done": "Reset Done",
        "records_saved": "{} records uploaded.",
        "addr_updated": "{} addresses updated.",
        "admin_menu": "Admin Menu",
        "demand_analysis": "Global Demand Analysis",
        "search_filter": "Search Filter",
        "tab_vehicle": "Vehicle",
        "tab_engine": "Engine",
        "tab_yard": "Yard",
        "manufacturer": "Manufacturer",
        "from_year": "From Year",
        "to_year": "To Year",
        "model": "Model",
        "engine_code": "Engine Code",
        "partner_name": "Partner Name",
        "search_btn_veh": "Search Vehicle",
        "search_btn_eng": "Search Engine",
        "search_btn_partners": "Search Partner",
        "reset_filters": "Reset Filters",
        "check_trends": "Check global search trends.",
        "show_trends": "Show Trends",
        "analysis_title": "Global Demand Trends (Real-time)",
        "top_engines": "Top Searched Engines",
        "top_models": "Top Searched Models",
        "main_title": "K-Used Car/Engine Inventory",
        "tab_inventory": "Inventory",
        "tab_orders": "Orders",
        "tab_results": "Search Results",
        "tab_my_orders": "My Orders",
        "no_results": "No results found.",
        "plz_select": "Please select filters from the sidebar to search.",
        "total_veh": "Total Vehicles",
        "matched_eng": "Matched Engines",
        "partners_cnt": "Partners",
        "real_yards": "Real Junkyards",
        "limit_warning": "⚠️ Showing top 5,000 results out of {:,}. Please refine filters.",
        "stock_by_partner": "Stock by Partner",
        "login_req_warn": "🔒 Login required to request a quote.",
        "selected_msg": "Selected: **{}** ({} EA)",
        "req_quote_title": "📨 Request Quote to {}",
        "name_company": "Name / Company",
        "contact": "Contact (Email/Phone) *",
        "qty": "Quantity *",
        "item": "Item *",
        "unit_price": "Target Unit Price (USD) *",
        "message": "Message to Admin",
        "send_btn": "🚀 Send Inquiry",
        "fill_error": "⚠️ Please fill in all required fields: Contact, Item, and Price.",
        "inquiry_sent": "✅ Inquiry has been sent to our sales team.",
        "item_list": "Item List",
        "incoming_quotes": "📩 Incoming Quote Requests",
        "my_quote_req": "🛒 My Quote Requests",
        "no_orders_admin": "No pending orders.",
        "no_orders_buyer": "You haven't requested any quotes yet.",
        "status_change": "Change Status",
        "update_btn": "Update",
        "updated_msg": "Updated!",
        "offer_received": "💬 Offer Received! Check your email/phone."
    },
    "Korean": {
        "app_title": "K-Used Car 글로벌 허브",
        "login_title": "로그인",
        "id": "아이디",
        "pw": "비밀번호",
        "sign_in": "로그인",
        "logout": "로그아웃",
        "welcome": "환영합니다, {}님!",
        "invalid_cred": "로그인 정보가 올바르지 않습니다.",
        "admin_tools": "관리자 도구",
        "data_upload": "데이터 업로드",
        "save_data": "데이터 저장",
        "addr_db": "주소 DB",
        "save_addr": "주소 저장",
        "reset_db": "DB 초기화",
        "reset_done": "초기화 완료",
        "records_saved": "{}건 저장 완료.",
        "addr_updated": "{}곳 주소 업데이트 완료.",
        "admin_menu": "관리자 메뉴",
        "demand_analysis": "글로벌 수요 분석",
        "search_filter": "검색 필터",
        "tab_vehicle": "차량",
        "tab_engine": "엔진",
        "tab_yard": "업체",
        "manufacturer": "제조사",
        "from_year": "시작 연식",
        "to_year": "종료 연식",
        "model": "모델명",
        "engine_code": "엔진코드",
        "partner_name": "파트너명",
        "search_btn_veh": "차량 검색",
        "search_btn_eng": "엔진 검색",
        "search_btn_partners": "파트너 검색",
        "reset_filters": "필터 초기화",
        "check_trends": "글로벌 검색 트렌드 확인",
        "show_trends": "트렌드 보기",
        "analysis_title": "글로벌 실시간 수요 분석",
        "top_engines": "인기 검색 엔진",
        "top_models": "인기 검색 차종",
        "main_title": "K-Used Car/Engine 재고 현황",
        "tab_inventory": "재고 조회",
        "tab_orders": "주문 관리",
        "tab_results": "검색 결과",
        "tab_my_orders": "내 주문 내역",
        "no_results": "검색 결과가 없습니다.",
        "plz_select": "사이드바에서 필터를 선택하여 검색하세요.",
        "total_veh": "총 차량",
        "matched_eng": "매칭 엔진",
        "partners_cnt": "파트너 수",
        "real_yards": "실제 폐차장",
        "limit_warning": "⚠️ 총 {:,}건 중 상위 5,000건만 표시됩니다. 필터를 상세 조정하세요.",
        "stock_by_partner": "업체별 보유 현황",
        "login_req_warn": "🔒 견적 요청을 위해 로그인이 필요합니다.",
        "selected_msg": "선택됨: **{}** ({} 개)",
        "req_quote_title": "📨 {}에 견적 요청",
        "name_company": "이름 / 회사명",
        "contact": "연락처 (이메일/전화) *",
        "qty": "요청 수량 *",
        "item": "품목 *",
        "unit_price": "희망 단가 (USD) *",
        "message": "메시지",
        "send_btn": "🚀 견적 요청 전송",
        "fill_error": "⚠️ 필수 입력 항목(연락처, 품목, 단가)을 입력해주세요.",
        "inquiry_sent": "✅ 영업팀으로 견적 요청이 전송되었습니다.",
        "item_list": "상세 목록",
        "incoming_quotes": "📩 접수된 견적 요청",
        "my_quote_req": "🛒 나의 견적 요청 내역",
        "no_orders_admin": "대기 중인 주문이 없습니다.",
        "no_orders_buyer": "아직 요청한 내역이 없습니다.",
        "status_change": "상태 변경",
        "update_btn": "업데이트",
        "updated_msg": "업데이트 완료!",
        "offer_received": "💬 견적 도착! 이메일/전화를 확인하세요."
    },
    "Russian": {
        "app_title": "K-Used Car Глобальный Хаб",
        "login_title": "Вход",
        "id": "ID",
        "pw": "Пароль",
        "sign_in": "Войти",
        "logout": "Выйти",
        "welcome": "Добро пожаловать, {}!",
        "invalid_cred": "Неверные учетные данные",
        "admin_tools": "Инструменты админа",
        "data_upload": "Загрузка данных",
        "save_data": "Сохранить данные",
        "addr_db": "БД Адресов",
        "save_addr": "Сохранить адрес",
        "reset_db": "Сброс БД",
        "reset_done": "Сброс выполнен",
        "records_saved": "{} записей загружено.",
        "addr_updated": "{} адресов обновлено.",
        "admin_menu": "Меню админа",
        "demand_analysis": "Анализ спроса",
        "search_filter": "Фильтр поиска",
        "tab_vehicle": "Автомобиль",
        "tab_engine": "Двигатель",
        "tab_yard": "Склад",
        "manufacturer": "Производитель",
        "from_year": "С года",
        "to_year": "По год",
        "model": "Модель",
        "engine_code": "Код двигателя",
        "partner_name": "Партнер",
        "search_btn_veh": "Поиск авто",
        "search_btn_eng": "Поиск двигателя",
        "search_btn_partners": "Поиск партнера",
        "reset_filters": "Сброс фильтров",
        "check_trends": "Глобальные тренды поиска",
        "show_trends": "Показать тренды",
        "analysis_title": "Анализ спроса в реальном времени",
        "top_engines": "Топ двигателей",
        "top_models": "Топ моделей",
        "main_title": "Инвентарь K-Used Car/Engine",
        "tab_inventory": "Инвентарь",
        "tab_orders": "Заказы",
        "tab_results": "Результаты",
        "tab_my_orders": "Мои заказы",
        "no_results": "Результатов не найдено.",
        "plz_select": "Выберите фильтры для поиска.",
        "total_veh": "Всего авто",
        "matched_eng": "Двигатели",
        "partners_cnt": "Партнеры",
        "real_yards": "Склады",
        "limit_warning": "⚠️ Показано топ 5,000 из {:,}. Уточните фильтры.",
        "stock_by_partner": "Наличие по партнерам",
        "login_req_warn": "🔒 Требуется вход для запроса цены.",
        "selected_msg": "Выбрано: **{}** ({} шт.)",
        "req_quote_title": "📨 Запрос цены у {}",
        "name_company": "Имя / Компания",
        "contact": "Контакт (Email/Тел) *",
        "qty": "Количество *",
        "item": "Товар *",
        "unit_price": "Целевая цена (USD) *",
        "message": "Сообщение админу",
        "send_btn": "🚀 Отправить запрос",
        "fill_error": "⚠️ Заполните обязательные поля: Контакт, Товар, Цена.",
        "inquiry_sent": "✅ Запрос отправлен в отдел продаж.",
        "item_list": "Список товаров",
        "incoming_quotes": "📩 Входящие запросы",
        "my_quote_req": "🛒 Мои запросы",
        "no_orders_admin": "Нет ожидающих заказов.",
        "no_orders_buyer": "Вы еще не делали запросов.",
        "status_change": "Изменить статус",
        "update_btn": "Обновить",
        "updated_msg": "Обновлено!",
        "offer_received": "💬 Предложение получено! Проверьте почту."
    },
    "Arabic": {
        "app_title": "K-Used Car Global Hub",
        "login_title": "تسجيل الدخول",
        "id": "المعرف",
        "pw": "كلمة المرور",
        "sign_in": "دخول",
        "logout": "خروج",
        "welcome": "مرحباً، {}!",
        "invalid_cred": "بيانات الاعتماد غير صالحة",
        "admin_tools": "أدوات المسؤول",
        "data_upload": "تحميل البيانات",
        "save_data": "حفظ البيانات",
        "addr_db": "قاعدة بيانات العناوين",
        "save_addr": "حفظ العنوان",
        "reset_db": "إعادة تعيين قاعدة البيانات",
        "reset_done": "تمت إعادة التعيين",
        "records_saved": "تم تحميل {} سجل.",
        "addr_updated": "تم تحديث {} عنوان.",
        "admin_menu": "قائمة المسؤول",
        "demand_analysis": "تحليل الطلب العالمي",
        "search_filter": "عامل تصفية البحث",
        "tab_vehicle": "مركبة",
        "tab_engine": "محرك",
        "tab_yard": "ساحة",
        "manufacturer": "الصانع",
        "from_year": "من سنة",
        "to_year": "إلى سنة",
        "model": "الموديل",
        "engine_code": "رمز المحرك",
        "partner_name": "اسم الشريك",
        "search_btn_veh": "بحث عن مركبة",
        "search_btn_eng": "بحث عن محرك",
        "search_btn_partners": "بحث عن شريك",
        "reset_filters": "إعادة تعيين المرشحات",
        "check_trends": "تحقق من اتجاهات البحث العالمية.",
        "show_trends": "عرض الاتجاهات",
        "analysis_title": "اتجاهات الطلب العالمي (مباشر)",
        "top_engines": "أفضل المحركات بحثًا",
        "top_models": "أفضل الموديلات بحثًا",
        "main_title": "مخزون السيارات/المحركات المستعملة الكورية",
        "tab_inventory": "المخزون",
        "tab_orders": "الطلبات",
        "tab_results": "نتائج البحث",
        "tab_my_orders": "طلباتي",
        "no_results": "لم يتم العثور على نتائج.",
        "plz_select": "يرجى تحديد مرشحات للبحث.",
        "total_veh": "إجمالي المركبات",
        "matched_eng": "المحركات المطابقة",
        "partners_cnt": "الشركاء",
        "real_yards": "ساحات الخردة الحقيقية",
        "limit_warning": "⚠️ يتم عرض أعلى 5000 نتيجة من {:,}. يرجى تحسين المرشحات.",
        "stock_by_partner": "المخزون حسب الشريك",
        "login_req_warn": "🔒 تسجيل الدخول مطلوب لطلب عرض أسعار.",
        "selected_msg": "محدد: **{}** ({} قطعة)",
        "req_quote_title": "📨 طلب عرض أسعار لـ {}",
        "name_company": "الاسم / الشركة",
        "contact": "الاتصال (بريد إلكتروني/هاتف) *",
        "qty": "الكمية *",
        "item": "العنصر *",
        "unit_price": "السعر المستهدف (دولار) *",
        "message": "رسالة للمسؤول",
        "send_btn": "🚀 إرسال الطلب",
        "fill_error": "⚠️ يرجى ملء الحقول المطلوبة: جهة الاتصال، العنصر، والسعر.",
        "inquiry_sent": "✅ تم إرسال الطلب إلى فريق المبيعات لدينا.",
        "item_list": "قائمة العناصر",
        "incoming_quotes": "📩 طلبات الأسعار الواردة",
        "my_quote_req": "🛒 طلبات الأسعار الخاصة بي",
        "no_orders_admin": "لا توجد طلبات معلقة.",
        "no_orders_buyer": "لم تقم بطلب أي عروض أسعار بعد.",
        "status_change": "تغيير الحالة",
        "update_btn": "تحديث",
        "updated_msg": "تم التحديث!",
        "offer_received": "💬 تم استلام العرض! تحقق من بريدك الإلكتروني/هاتفك."
    }
}

def create_db():
    conn = sqlite3.connect('translations.db')
    c = conn.cursor()
    c.execute('''CREATE TABLE IF NOT EXISTS translations (
        key TEXT PRIMARY KEY,
        English TEXT,
        Korean TEXT,
        Russian TEXT,
        Arabic TEXT
    )''')
    
    # 데이터 변환 (Nested Dictionary -> List of Tuples)
    keys = RAW_DATA["English"].keys()
    data_to_insert = []
    
    for k in keys:
        row = (
            k,
            RAW_DATA.get("English", {}).get(k, k),
            RAW_DATA.get("Korean", {}).get(k, k),
            RAW_DATA.get("Russian", {}).get(k, k),
            RAW_DATA.get("Arabic", {}).get(k, k)
        )
        data_to_insert.append(row)
        
    c.executemany("INSERT OR REPLACE INTO translations VALUES (?, ?, ?, ?, ?)", data_to_insert)
    conn.commit()
    conn.close()
    print("✅ translations.db created successfully!")

if __name__ == "__main__":
    create_db()